## If you want to use one of the kitchen-docker* drivers...
### You should rename this file to: .kitchen.local.yml
### OR:
###   export KITCHEN_LOCAL_YAML=.kitchen.docker.local.yml
### Hint: Make sure you have kitchen-docker and kitchen-docker-api gems installed
### Then set DOCKER_HOST=tcp://my-docker-host.example.com:4243
---
#driver_plugin: docker
driver:
  name: docker
  use_sudo: false
  provision_command:
    - 'curl -L http://www.opscode.com/chef/install.sh | bash'

<% unless ENV['KITCHEN_HTTP_PROXY'].nil? %>
  http_proxy: <%= ENV['KITCHEN_HTTP_PROXY'] %>
  links: "polipo:polipo"
<% end %>
<% unless ENV['KITCHEN_HTTP_PROXY'].nil? && ENV['KITCHEN_HTTPS_PROXY'].nil? %>
  https_proxy: <%= ENV['KITCHEN_HTTPS_PROXY'].nil? ? ENV['KITCHEN_HTTP_PROXY'] : ENV['KITCHEN_HTTPS_PROXY'] %>
<% end %>

  driver_config:
    hostname: kitchen
    use_sudo: true
    require_chef_omnibus: false
    provision_command:
      - 'curl -L http://www.opscode.com/chef/install.sh | bash'


provisioner:
  require_chef_omnibus: false
  chef_omnibus_root: /opt/chef
<% unless ENV['KITCHEN_HTTP_PROXY'].nil? && ENV['KITCHEN_HTTPS_PROXY'].nil? %>
  chef_omnibus_url: "http://www.getchef.com/chef/install.sh"
  client_rb:
    http_proxy: <%= ENV['KITCHEN_HTTP_PROXY'] %>
    https_proxy: <%= ENV['KITCHEN_HTTPS_PROXY'].nil? ? ENV['KITCHEN_HTTP_PROXY'] : ENV['KITCHEN_HTTPS_PROXY'] %>
<% end %>

platforms:
## Trusty Tahr LTS
- name: ubuntu-14.04
## Vivid Vervet ## EOL January 2016
- name: ubuntu-15.04
<% unless ENV['KITCHEN_HTTP_PROXY'].nil? %>
  links: "polipo:polipo"
<% end %>
## Xenial Xerus
- name: ubuntu-16.04
<% unless ENV['KITCHEN_HTTP_PROXY'].nil? %>
  links: "polipo:polipo"
<% end %>

