---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[kodi-tests::default]
      - recipe[kodi::default]
      - recipe[export-node]
    attributes:
  - name: pvr-addons
    run_list:
      - recipe[kodi-tests::default]
      - recipe[kodi::default]
      - recipe[export-node]
    attributes:
      kodi:
        addons:
          - kodi-pvr-dev
          - kodi-pvr-argustv
          - kodi-pvr-demo
          - kodi-pvr-dvblink
          - kodi-pvr-dvbviewer
          - kodi-pvr-filmon
          - kodi-pvr-iptvsimple
          - kodi-pvr-mediaportal-tvserver
          - kodi-pvr-mythtv
          - kodi-pvr-nextpvr
          - kodi-pvr-njoy
          - kodi-pvr-pctv
          - kodi-pvr-stalker
          - kodi-pvr-vbox
          - kodi-pvr-vdr-vnsi
          - kodi-pvr-vuplus
          - kodi-pvr-wmc
#          - kodi-pvr-hts ## Conflicts w/ kodi-pvr-wmc

