---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[kodi-tests::default]
      - recipe[kodi::default]
      - recipe[export-node]
    attributes:
  - name: pvr-mythtv
    run_list:
      - recipe[kodi-tests::default]
      - recipe[kodi::default]
      - recipe[export-node]
    attributes:
      kodi:
        addons:
          - kodi-pvr-mythtv
