language: generic

sudo: required
services: docker

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"
  matrix:
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-ubuntu-1710
  - INSTANCE=pvr-addons-ubuntu-1404
  - INSTANCE=pvr-addons-ubuntu-1604

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk
before_install:
  - "openssl aes-256-cbc -K $encrypted_f55cd78cfa98_key -iv $encrypted_f55cd78cfa98_iv -in client.pem.enc -out client.pem -d"

before_script:
  - eval "$(chef shell-init $(basename $SHELL))"
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - /opt/chefdk/embedded/bin/chef gem install kitchen-docker

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - rake test
  - KITCHEN_LOCAL_YAML=.kitchen.docker.local.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

deploy:
  provider: chef-supermarket
  user_id: "jcuzella"
  client-key: client.pem
  cookbook_category: "Applications"
  on:
    tags: true
