language: generic

sudo: required
services: docker

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"
  matrix:
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1504
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=pvr-addons-ubuntu-1404
  - INSTANCE=pvr-addons-ubuntu-1504

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

before_script:
  - eval "$(chef shell-init $(basename $SHELL))"
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - /opt/chefdk/embedded/bin/chef gem install kitchen-docker

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - rake test
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

